### PR TITLE
Switch source to GitHub and some clean up

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This merge also adds @xylar as a maintainer

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
Looking at the `recipe` directory, it seemed like a bunch of files from the repo base directory must have accidentally got copied there in https://github.com/conda-forge/zoltan-feedstock/pull/2.  I've removed those here.

The main change in this PR, though, is to point to the current development location: https://github.com/sandialabs/Zoltan.  This is in anticipation of updating to v3.90 as soon as this merge goes in.

**Comment by xylar** [comment]
@conda-forge/zoltan, this is ready to review.  Please let me know if you're open to adding another maintainer to the already fairly long list.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Review by cekees — APPROVED** [review]
Looks good to me. Thank you.

**Comment by cekees** [comment]
@JohanMabille these are really simple conflicts due to the source update, so I think @xylar can just resolve via github, but I wanted to check with somebody who understands the conda-forge tooling better than idea.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
The cleanest way to handle these conflicts is to rebase, remove previous rerender commits, force push, and ask the bot to rerender again.  This is what I have just done.  Once the tests have passed, I believe this will be ready to merge.

**Comment by xylar** [comment]
@conda-forge/zoltan, this is ready to review and merge.

**Pull request merged**
