### PR TITLE
add linux_ppc64le, linux_aarch64, osx_arm64  archs

### PR DESCRIPTION
**Pull request by matthiasdiener**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
This is ready for review @conda-forge/zoltan

**Review by xylar — APPROVED** [review]
@matthiasdiener, wonderful! Looks good to me.  I'll merge soon unless I hear objections.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@matthiasdiener, hmm, I missed the fact that you hadn't actually rerendered and thus CI has not yet been building with the new architectures.  Please be careful to check that box only if you did rerender (after making changes).

**Review by xylar — COMMENTED** [review]
Revoking my approval until CI finishes after a rerender.

**Comment by xylar** [comment]
Oh, sorry, my mistake.  The rerender obviously got packaged into one of the other commits.

**Comment by xylar** [comment]
I'm going to go ahead and merge.  Sorry for the noise on not rerendering.

**Comment by matthiasdiener** [comment]
> I'm going to go ahead and merge. Sorry for the noise on not rerendering.

No worries, thank you for merging!

**Pull request merged**
